name=PCF8575_LCD+clavier
version=2.0.0
author=TPignol
sentence=PCF8575 + HD44780 LCD library + clavier matricielle
paragraph=ESP32/Arduino library for HD44780 displays via PCF8575.
category=Display
architectures=*
