name=PCF8575_LCD_V2
version=1.2.0
author=tpignol
maintainer=tpignol
sentence=Pilotage d'afficheurs LCD HD44780 et de claviers matriciels via un expandeur I2C PCF8575.
paragraph=Bibliotheque legere permettant de piloter un afficheur LCD HD44780 en mode 4 bits, un clavier matriciel et des E/S supplementaires a l'aide d'un PCF8575. Compatible AVR, ESP8266 et ESP32.
category=Display
url=https://github.com/tpignol/PCF8575_LCD_V2
architectures=*
depends=Wire